# Site settings
name: Matthew Kosloski
email: hi@mtk.me
url: http://matthewkosloski.me
description: "My name is Matthew, and I'm a 17-year-old front-end web developer and designer from Chicago. I specialize in front-end development, responsive web design, and search engine optimization."
timezone: America/Chicago
include: ['.htaccess']
port: 4001
dribbble: matthewkosloski
instagram: matthewkosloski
twitter: _mkos

permalink: /:categories/:title

gems: [nokogiri]

# Build settings
markdown: kramdown

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/feed.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
