# Site settings
name: Matthew Kosloski
email: hi@mtk.me
# Don't include trailing slack '/' at end of URL
url: http://matthewkosloski.me
description: "My name is Matthew, and I'm a 17-year-old front-end web developer and designer from Chicago. I specialize in front-end development, responsive web design, and search engine optimization."
timezone: America/Chicago
include: ['.htaccess']
port: 4000

# Variables
dribbble: matthewkosloski
instagram: matthewkosloski
twitter: _mkos
color: df4747
keywords: "web designer, web developer, matthew kosloski, front-end development, css3, html5, dribbble, twitter, instagram, javascript, search engine optimization, jquery, responsive web design"

permalink: /:categories/:title

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

# Plugins
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/feed.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: false
  sources:
    - _assets/js
    - _assets/scss
  cachebust: none
